// Generated by gencpp from file dh_hand_driver/ActuateHandFeedback.msg
// DO NOT EDIT!


#ifndef DH_HAND_DRIVER_MESSAGE_ACTUATEHANDFEEDBACK_H
#define DH_HAND_DRIVER_MESSAGE_ACTUATEHANDFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dh_hand_driver
{
template <class ContainerAllocator>
struct ActuateHandFeedback_
{
  typedef ActuateHandFeedback_<ContainerAllocator> Type;

  ActuateHandFeedback_()
    : position_reached(false)  {
    }
  ActuateHandFeedback_(const ContainerAllocator& _alloc)
    : position_reached(false)  {
  (void)_alloc;
    }



   typedef uint8_t _position_reached_type;
  _position_reached_type position_reached;





  typedef boost::shared_ptr< ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ActuateHandFeedback_

typedef ::dh_hand_driver::ActuateHandFeedback_<std::allocator<void> > ActuateHandFeedback;

typedef boost::shared_ptr< ::dh_hand_driver::ActuateHandFeedback > ActuateHandFeedbackPtr;
typedef boost::shared_ptr< ::dh_hand_driver::ActuateHandFeedback const> ActuateHandFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator1> & lhs, const ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.position_reached == rhs.position_reached;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator1> & lhs, const ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dh_hand_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3bc153b3a5101bcfc1c76fc2c8373082";
  }

  static const char* value(const ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3bc153b3a5101bcfULL;
  static const uint64_t static_value2 = 0xc1c76fc2c8373082ULL;
};

template<class ContainerAllocator>
struct DataType< ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dh_hand_driver/ActuateHandFeedback";
  }

  static const char* value(const ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# feedback definition\n"
"\n"
"bool position_reached\n"
"\n"
;
  }

  static const char* value(const ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position_reached);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActuateHandFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dh_hand_driver::ActuateHandFeedback_<ContainerAllocator>& v)
  {
    s << indent << "position_reached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.position_reached);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DH_HAND_DRIVER_MESSAGE_ACTUATEHANDFEEDBACK_H
