// Generated by gencpp from file dh_hand_driver/ActuateHandActionGoal.msg
// DO NOT EDIT!


#ifndef DH_HAND_DRIVER_MESSAGE_ACTUATEHANDACTIONGOAL_H
#define DH_HAND_DRIVER_MESSAGE_ACTUATEHANDACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <dh_hand_driver/ActuateHandGoal.h>

namespace dh_hand_driver
{
template <class ContainerAllocator>
struct ActuateHandActionGoal_
{
  typedef ActuateHandActionGoal_<ContainerAllocator> Type;

  ActuateHandActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  ActuateHandActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::dh_hand_driver::ActuateHandGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ActuateHandActionGoal_

typedef ::dh_hand_driver::ActuateHandActionGoal_<std::allocator<void> > ActuateHandActionGoal;

typedef boost::shared_ptr< ::dh_hand_driver::ActuateHandActionGoal > ActuateHandActionGoalPtr;
typedef boost::shared_ptr< ::dh_hand_driver::ActuateHandActionGoal const> ActuateHandActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator1> & lhs, const ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator1> & lhs, const ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dh_hand_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "40af3aa9a12a00f83f82d66fd97d6d62";
  }

  static const char* value(const ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x40af3aa9a12a00f8ULL;
  static const uint64_t static_value2 = 0x3f82d66fd97d6d62ULL;
};

template<class ContainerAllocator>
struct DataType< ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dh_hand_driver/ActuateHandActionGoal";
  }

  static const char* value(const ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ActuateHandGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: dh_hand_driver/ActuateHandGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Command to control the GRIPPERS\n"
"# author: Jie Sun <jie.sun@dh-robotics.com>, AUG 2018\n"
"# Copyright @ DH-Robotics\n"
"\n"
"\n"
"# goal definition\n"
"\n"
"int32 MotorID\n"
"int32 force\n"
"int32 position\n"
"\n"
;
  }

  static const char* value(const ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActuateHandActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dh_hand_driver::ActuateHandActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::dh_hand_driver::ActuateHandGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DH_HAND_DRIVER_MESSAGE_ACTUATEHANDACTIONGOAL_H
