// Generated by gencpp from file dh_hand_driver/hand_stateRequest.msg
// DO NOT EDIT!


#ifndef DH_HAND_DRIVER_MESSAGE_HAND_STATEREQUEST_H
#define DH_HAND_DRIVER_MESSAGE_HAND_STATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dh_hand_driver
{
template <class ContainerAllocator>
struct hand_stateRequest_
{
  typedef hand_stateRequest_<ContainerAllocator> Type;

  hand_stateRequest_()
    : get_target(0)  {
    }
  hand_stateRequest_(const ContainerAllocator& _alloc)
    : get_target(0)  {
  (void)_alloc;
    }



   typedef int32_t _get_target_type;
  _get_target_type get_target;





  typedef boost::shared_ptr< ::dh_hand_driver::hand_stateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dh_hand_driver::hand_stateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct hand_stateRequest_

typedef ::dh_hand_driver::hand_stateRequest_<std::allocator<void> > hand_stateRequest;

typedef boost::shared_ptr< ::dh_hand_driver::hand_stateRequest > hand_stateRequestPtr;
typedef boost::shared_ptr< ::dh_hand_driver::hand_stateRequest const> hand_stateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dh_hand_driver::hand_stateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dh_hand_driver::hand_stateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dh_hand_driver::hand_stateRequest_<ContainerAllocator1> & lhs, const ::dh_hand_driver::hand_stateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.get_target == rhs.get_target;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dh_hand_driver::hand_stateRequest_<ContainerAllocator1> & lhs, const ::dh_hand_driver::hand_stateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dh_hand_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dh_hand_driver::hand_stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dh_hand_driver::hand_stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dh_hand_driver::hand_stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dh_hand_driver::hand_stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dh_hand_driver::hand_stateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dh_hand_driver::hand_stateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dh_hand_driver::hand_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6233a3f9e363265b1141787d0572c019";
  }

  static const char* value(const ::dh_hand_driver::hand_stateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6233a3f9e363265bULL;
  static const uint64_t static_value2 = 0x1141787d0572c019ULL;
};

template<class ContainerAllocator>
struct DataType< ::dh_hand_driver::hand_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dh_hand_driver/hand_stateRequest";
  }

  static const char* value(const ::dh_hand_driver::hand_stateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dh_hand_driver::hand_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
"\n"
"\n"
"int32 get_target\n"
;
  }

  static const char* value(const ::dh_hand_driver::hand_stateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dh_hand_driver::hand_stateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.get_target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hand_stateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dh_hand_driver::hand_stateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dh_hand_driver::hand_stateRequest_<ContainerAllocator>& v)
  {
    s << indent << "get_target: ";
    Printer<int32_t>::stream(s, indent + "  ", v.get_target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DH_HAND_DRIVER_MESSAGE_HAND_STATEREQUEST_H
