// Generated by gencpp from file dh_hand_driver/hand_stateResponse.msg
// DO NOT EDIT!


#ifndef DH_HAND_DRIVER_MESSAGE_HAND_STATERESPONSE_H
#define DH_HAND_DRIVER_MESSAGE_HAND_STATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dh_hand_driver
{
template <class ContainerAllocator>
struct hand_stateResponse_
{
  typedef hand_stateResponse_<ContainerAllocator> Type;

  hand_stateResponse_()
    : return_data(0)  {
    }
  hand_stateResponse_(const ContainerAllocator& _alloc)
    : return_data(0)  {
  (void)_alloc;
    }



   typedef int32_t _return_data_type;
  _return_data_type return_data;





  typedef boost::shared_ptr< ::dh_hand_driver::hand_stateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dh_hand_driver::hand_stateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct hand_stateResponse_

typedef ::dh_hand_driver::hand_stateResponse_<std::allocator<void> > hand_stateResponse;

typedef boost::shared_ptr< ::dh_hand_driver::hand_stateResponse > hand_stateResponsePtr;
typedef boost::shared_ptr< ::dh_hand_driver::hand_stateResponse const> hand_stateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dh_hand_driver::hand_stateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dh_hand_driver::hand_stateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dh_hand_driver::hand_stateResponse_<ContainerAllocator1> & lhs, const ::dh_hand_driver::hand_stateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.return_data == rhs.return_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dh_hand_driver::hand_stateResponse_<ContainerAllocator1> & lhs, const ::dh_hand_driver::hand_stateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dh_hand_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dh_hand_driver::hand_stateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dh_hand_driver::hand_stateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dh_hand_driver::hand_stateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dh_hand_driver::hand_stateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dh_hand_driver::hand_stateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dh_hand_driver::hand_stateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dh_hand_driver::hand_stateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55ce452b9e7e6cb141ddefb6a843a784";
  }

  static const char* value(const ::dh_hand_driver::hand_stateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55ce452b9e7e6cb1ULL;
  static const uint64_t static_value2 = 0x41ddefb6a843a784ULL;
};

template<class ContainerAllocator>
struct DataType< ::dh_hand_driver::hand_stateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dh_hand_driver/hand_stateResponse";
  }

  static const char* value(const ::dh_hand_driver::hand_stateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dh_hand_driver::hand_stateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 return_data\n"
;
  }

  static const char* value(const ::dh_hand_driver::hand_stateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dh_hand_driver::hand_stateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.return_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hand_stateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dh_hand_driver::hand_stateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dh_hand_driver::hand_stateResponse_<ContainerAllocator>& v)
  {
    s << indent << "return_data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.return_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DH_HAND_DRIVER_MESSAGE_HAND_STATERESPONSE_H
